# Generated by Django 5.1.7 on 2025-03-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='image',
        ),
    ]
