# Generated by Django 5.1.7 on 2025-03-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_remove_livre_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='categorie_id',
            new_name='genre_id',
        ),
    ]
