# Generated by Django 5.1.7 on 2025-03-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_rename_categorie_genre_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
