# Generated by Django 5.1.7 on 2025-03-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
